"""Generate Python signatures/type stubs from MCP tool schemas."""

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import NamedTuple

from mcp import Tool

from monty.mcp_tool import tool_properties

# Canonical JSON Schema type -> Python type string
_SCALAR = {"number": "float", "integer": "int", "string": "str", "boolean": "bool", "null": "None"}
_COMPLEX_MARKERS = ("oneOf", "anyOf", "allOf", "$ref", "enum", "const", "patternProperties", "if", "then", "else")


class ToolTyping(NamedTuple):
    signature: str
    helper_code: str
    payload_param: bool


def _schema_to_type(schema: dict | None) -> str:
    if not schema or not isinstance(schema, dict):
        return "dict"
    kind = schema.get("type")
    if kind in _SCALAR:
        return _SCALAR[kind]
    if kind == "array":
        items = schema.get("items")
        return f"list[{_schema_to_type(items) if isinstance(items, dict) else 'object'}]"
    if kind == "object":
        props = schema.get("properties") or {}
        if not props:
            return "dict"
        value_types = [_schema_to_type(p) for _, p in sorted(props.items(), key=lambda x: x[0]) if isinstance(p, dict)]
        if len(value_types) == 1:
            t = value_types[0]
            return t if t in _SCALAR.values() else f"dict[str, {t}]"
        return "dict[str, object]" if len(value_types) > 1 else "dict"
    return "dict"


def _contains_complex_markers(schema: dict | None) -> bool:
    if not isinstance(schema, dict):
        return False
    if any(marker in schema for marker in _COMPLEX_MARKERS):
        return True
    for value in schema.values():
        if isinstance(value, dict) and _contains_complex_markers(value):
            return True
        if isinstance(value, list) and any(isinstance(i, dict) and _contains_complex_markers(i) for i in value):
            return True
    return False


def _is_simple_schema(schema: dict | None) -> bool:
    if not isinstance(schema, dict):
        return False
    if _contains_complex_markers(schema):
        return False
    kind = schema.get("type")
    if kind in _SCALAR:
        return True
    if kind == "array":
        items = schema.get("items")
        return isinstance(items, dict) and _is_simple_schema(items)
    if kind == "object":
        props = schema.get("properties")
        if props is None:
            return True
        if not isinstance(props, dict):
            return False
        return all(isinstance(v, dict) and _is_simple_schema(v) for v in props.values())
    return False


def _to_pascal_case(name: str) -> str:
    parts = [p for p in re.split(r"[^0-9A-Za-z]+", name) if p]
    base = "".join(p[:1].upper() + p[1:] for p in parts) or "Tool"
    if base[0].isdigit():
        return f"Tool{base}"
    return base


def _sanitize_generated_module(code: str) -> str:
    lines: list[str] = []
    for line in code.splitlines():
        stripped = line.strip()
        if stripped.startswith("# generated by datamodel-codegen:"):
            continue
        if stripped.lstrip("#").strip().startswith("filename:"):
            continue
        if stripped.lstrip("#").strip().startswith("timestamp:"):
            continue
        if stripped == "from __future__ import annotations":
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def _generate_typed_dict(schema: dict, class_name: str) -> str:
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        input_path = temp_path / "schema.json"
        output_path = temp_path / "models.py"
        input_path.write_text(json.dumps(schema), encoding="utf-8")
        subprocess.run(
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                "--input",
                str(input_path),
                "--input-file-type",
                "jsonschema",
                "--output-model-type",
                "typing.TypedDict",
                "--class-name",
                class_name,
                "--output",
                str(output_path),
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        return _sanitize_generated_module(output_path.read_text(encoding="utf-8"))


def _type_and_helpers(schema: dict | None, class_name: str) -> tuple[str, str]:
    if not isinstance(schema, dict) or not schema:
        return "dict", ""
    if _is_simple_schema(schema):
        return _schema_to_type(schema), ""
    try:
        return class_name, _generate_typed_dict(schema, class_name)
    except Exception:
        # Keep type checking resilient even if external codegen fails locally.
        return "dict", ""


def mcp_tool_typing(tool: Tool) -> ToolTyping:
    tool_base = _to_pascal_case(tool.name)
    input_schema = tool.inputSchema if isinstance(tool.inputSchema, dict) else {}
    output_schema = tool.outputSchema if isinstance(getattr(tool, "outputSchema", None), dict) else None
    helper_sections: list[str] = []

    if _is_simple_schema(input_schema) and input_schema.get("type") == "object":
        props = tool_properties(tool)
        if props:
            params = ", ".join(f"{name}: {_schema_to_type(schema)}" for name, schema in sorted(props.items()))
        else:
            params = ""
        payload_param = False
    elif not input_schema:
        params = ""
        payload_param = False
    else:
        in_type, in_helper = _type_and_helpers(input_schema, f"{tool_base}Input")
        params = f"payload: {in_type}"
        payload_param = True
        if in_helper:
            helper_sections.append(in_helper)

    out_type, out_helper = _type_and_helpers(output_schema, f"{tool_base}Output")
    if out_helper:
        helper_sections.append(out_helper)

    return ToolTyping(
        signature=f"async def {tool.name}({params}) -> {out_type}",
        helper_code="\n\n".join(s for s in helper_sections if s),
        payload_param=payload_param,
    )


def mcp_tool_signature(tool: Tool) -> str:
    typing = mcp_tool_typing(tool)
    # Include referenced types so discovery explains dictionary payload fields.
    return "\n\n".join(part for part in (typing.helper_code, typing.signature) if part)
