import type { ThreadLabels } from "@/components/assistant-ui/elements/thread.aui"
import type { Locale } from "@/lib/i18n/config"

export const threadLabels: Record<Locale, ThreadLabels> = {
  en: {
    loadingConversation: "Loading conversation",
    scrollToBottom: "Scroll to bottom",
    welcome: "What would you like to work on?",
    composerPlaceholder: "Message",
    messageInput: "Message input",
    voiceInput: "Voice input",
    startVoiceInput: "Start voice input",
    stopDictation: "Stop dictation",
    stopVoiceInput: "Stop voice input",
    sendMessage: "Send message",
    stopGenerating: "Stop generating",
    assistantWorking: "Agent is working",
    copy: "Copy",
    refresh: "Retry response",
    more: "More actions",
    exportMarkdown: "Export as Markdown",
    edit: "Edit message",
    pendingInteractionAction:
      "Answer the pending question before changing this conversation",
    cancel: "Cancel",
    update: "Update",
    historySearch: "Search conversation history",
    historySearchPlaceholder: "Filter sent messages…",
    historyCancel: "Cancel history search",
    queuedMessages: "Queued messages",
    previous: "Previous branch",
    next: "Next branch",
    conversationHeading: "Conversation",
    modelSelector: "Choose model",
    slashCommands: "Slash commands",
    contextUsage: "Context usage",
    contextTitle: "Context",
    contextSystem: "System",
    contextTools: "Tools",
    contextMessages: "Messages",
    contextTotal: "Total",
    conversationSearch: {
      search: "Search in conversation",
      placeholder: "Find in conversation…",
      previous: "Previous result",
      next: "Next result",
      close: "Close search",
      results: (index, count) => `${index} of ${count}`,
    },
    openSource: "Open source",
    documentSource: "Source document",
    attachments: {
      add: "Add attachment",
      remove: "Remove attachment",
      preview: "Attachment preview",
      image: "Image attachment",
      document: "Document attachment",
      file: "File attachment",
      uploading: "Uploading",
      uploadFailed: "Upload failed",
    },
  },
  he: {
    loadingConversation: "השיחה נטענת",
    scrollToBottom: "גלילה לתחתית",
    welcome: "על מה תרצו לעבוד?",
    composerPlaceholder: "הודעה",
    messageInput: "שדה הודעה",
    voiceInput: "קלט קולי",
    startVoiceInput: "התחלת קלט קולי",
    stopDictation: "עצירת הכתבה",
    stopVoiceInput: "עצירת קלט קולי",
    sendMessage: "שליחת הודעה",
    stopGenerating: "עצירת התשובה",
    assistantWorking: "הסוכן עובד",
    copy: "העתקה",
    refresh: "ניסיון חוזר",
    more: "פעולות נוספות",
    exportMarkdown: "ייצוא כ-Markdown",
    edit: "עריכת ההודעה",
    pendingInteractionAction: "יש לענות על השאלה הממתינה לפני שינוי השיחה",
    cancel: "ביטול",
    update: "עדכון",
    historySearch: "חיפוש בהיסטוריית השיחה",
    historySearchPlaceholder: "סינון הודעות שנשלחו…",
    historyCancel: "ביטול חיפוש בהיסטוריה",
    queuedMessages: "הודעות בתור",
    previous: "הסתעפות קודמת",
    next: "הסתעפות הבאה",
    conversationHeading: "שיחה",
    modelSelector: "בחירת מודל",
    slashCommands: "פקודות קו נטוי",
    contextUsage: "שימוש בהקשר",
    contextTitle: "הקשר",
    contextSystem: "מערכת",
    contextTools: "כלים",
    contextMessages: "הודעות",
    contextTotal: "סה״כ",
    conversationSearch: {
      search: "חיפוש בשיחה",
      placeholder: "חיפוש בשיחה…",
      previous: "תוצאה קודמת",
      next: "תוצאה הבאה",
      close: "סגירת החיפוש",
      results: (index, count) => `${index} מתוך ${count}`,
    },
    openSource: "פתיחת מקור",
    documentSource: "מסמך מקור",
    attachments: {
      add: "הוספת קובץ מצורף",
      remove: "הסרת קובץ מצורף",
      preview: "תצוגה מקדימה של קובץ מצורף",
      image: "תמונה מצורפת",
      document: "מסמך מצורף",
      file: "קובץ מצורף",
      uploading: "בהעלאה",
      uploadFailed: "ההעלאה נכשלה",
    },
  },
}
